### ISSUE TITLE
Doesn't work for new Twitter redesign

### ISSUE THREAD

**Issue by bryanbraun** [HollyAdele/twitter-newsfeed-eradicator#3]
When you opt in to the new twitter redesign, and the timeline is not longer suppressed:

![image](https://user-images.githubusercontent.com/1256329/53102474-bafaa400-34f9-11e9-8211-d1ed9f41fd81.png)

**Comment by yolfer** [comment]
+1. I wonder if this extension is abandonware?

**Comment by HollyAdele** [comment]
Rats!

Thanks for letting me know. Now accepting pull requests!

**Comment by yolfer** [comment]
Hi Holly! I take back what I said about "abandonware". Thanks for creating this in the first place. Hopefully someone will come along with the bandwidth to update.

**Comment by HollyAdele** [comment]
I'm going to archive this project but anyone is welcome to resurrect it.

**Comment by HollyAdele** [comment]
This is fixed in https://github.com/HollyAdele/twitter-newsfeed-eradicator/pull/4.
